### ISSUE TITLE
Some Items are missing

### ISSUE THREAD

**Issue by xSuperr** [pmmp/BedrockData#14]
Some Items (Amethyst and The Chain Item (Not Block)) are missing from the resources. Those are the only ones I have found so far.

Chain Item = -503 [255 - 758] https://minecraft.fandom.com/wiki/Chain#ID
Amethyst = -327 [255 - 582] https://minecraft.fandom.com/wiki/Block_of_Amethyst#ID

Is there a reason some of these items are not added or is it because they were forgotten?

**Comment by dktapps** [comment]
Item IDs are dynamic since several versions back. Only the legacy numeric ones are included.
