### ISSUE TITLE
Question: schema of required_item_list.json

### ISSUE THREAD

**Issue by johnbanq** [pmmp/BedrockData#23]
Hi!

I am curious about the content of required_item_list.json. What does the data inside them mean?

It would be great if we can have a short explanation of it in the README.md

I have tried looking for explanations in the commit history, any references in this repo or [bds-mod-mapping](https://github.com/pmmp/bds-mod-mapping) but couldn't find any.

Thanks in advance!

**Comment by dktapps** [comment]
`id` is the associated dynamic numeric id used on the wire. `component_based` is whether an ItemComponentPacket is required to fully define that item type. It's basically the item data you'd find in a StartGamePacket.
